import argparse
import csv
import glob
import json
import logging
import os
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape as xml_escape
from urllib.parse import quote

import pandas as pd
import requests
import yaml
from Bio import SeqIO
from tqdm import tqdm

from ftscripts import files


UNIPROT_NS = {'up': 'http://uniprot.org/uniprot'}
UNKNOWN = 'Unknown'
CHEBI_SOAP_URL = 'https://www.ebi.ac.uk/webservices/chebi/2.0/webservice'
CHEBI_REST_URL = 'https://www.ebi.ac.uk/chebi/backend/api/public/compound'
RHEA_TABLE_URL = 'https://www.rhea-db.org/rhea/'
LOCAL_LIGAND_SMILES = {
    'Mn(2+)': '[Mn+2]',
    'Mn2+': '[Mn+2]',
    'Mn': '[Mn+2]',
    'K(+)': '[K+]',
    'K+': '[K+]',
    'K': '[K+]',
    'NH4(+)': '[NH4+]',
    'NH4+': '[NH4+]',
    'Mg(2+)': '[Mg+2]',
    'Mg2+': '[Mg+2]',
    'Mg': '[Mg+2]',
    'Zn(2+)': '[Zn+2]',
    'Zn2+': '[Zn+2]',
    'Zn': '[Zn+2]',
    'Fe(2+)': '[Fe+2]',
    'Fe2+': '[Fe+2]',
    'Fe(3+)': '[Fe+3]',
    'Fe3+': '[Fe+3]',
    'Ca(2+)': '[Ca+2]',
    'Ca2+': '[Ca+2]',
    'Na(+)': '[Na+]',
    'Na+': '[Na+]',
    'Cu(2+)': '[Cu+2]',
    'Cu2+': '[Cu+2]',
    'Co(2+)': '[Co+2]',
    'Co2+': '[Co+2]',
    'Ni(2+)': '[Ni+2]',
    'Ni2+': '[Ni+2]',
}


def get_structures_module():
    """
    Import ftscripts.structures only when pocket parsing/execution is needed.

    :return: Imported ftscripts.structures module.
    """
    from ftscripts import structures
    return structures


def create_boltz_folders(structures_dir):
    """
    Create the standalone Boltz directory tree inside a FastTarget structures folder.

    :param structures_dir: Path to organism/<organism>/structures.
    :return: Dictionary with key output directories.
    """
    boltz_dir = os.path.join(structures_dir, 'boltz')
    dirs = {
        'boltz': boltz_dir,
        'inputs': os.path.join(boltz_dir, 'inputs'),
        'results': os.path.join(boltz_dir, 'results'),
        'models': os.path.join(boltz_dir, 'models'),
        'pockets': os.path.join(boltz_dir, 'pockets'),
    }
    for directory in dirs.values():
        os.makedirs(directory, exist_ok=True)
    return dirs


def infer_organism_name(output_path=None, organism_name=None, structures_dir=None):
    """
    Resolve organism name and structures directory from user inputs.

    :param output_path: FastTarget output directory containing organism folders.
    :param organism_name: Organism name used in the FastTarget run.
    :param structures_dir: Direct path to organism/<organism>/structures.
    :return: Tuple with organism name and absolute structures directory.
    """
    if structures_dir:
        structures_dir = os.path.abspath(structures_dir)
        organism_dir = os.path.dirname(structures_dir)
        return os.path.basename(organism_dir), structures_dir

    if not output_path or not organism_name:
        raise ValueError('Provide either --structures-dir or both --output-path and --organism-name.')

    structures_dir = os.path.join(os.path.abspath(output_path), organism_name, 'structures')
    return organism_name, structures_dir


def find_gbk_file(output_path=None, organism_name=None, gbk_file=None, structures_dir=None):
    """
    Find the GenBank file used by FastTarget.

    :param output_path: FastTarget output directory containing organism folders.
    :param organism_name: Organism name used in the FastTarget run.
    :param gbk_file: Explicit GenBank file path.
    :param structures_dir: Direct path to organism/<organism>/structures.
    :return: Path to the GenBank file.
    """
    if gbk_file:
        gbk_file = os.path.abspath(gbk_file)
        if not os.path.isfile(gbk_file):
            raise FileNotFoundError(f'GBK file not found: {gbk_file}')
        return gbk_file

    candidates = []
    if output_path and organism_name:
        organism_dir = os.path.join(os.path.abspath(output_path), organism_name)
        candidates.extend([
            os.path.join(organism_dir, 'genome', f'{organism_name}.gbk'),
            os.path.join(organism_dir, f'{organism_name}.gbk'),
        ])
    if structures_dir:
        organism_dir = os.path.dirname(os.path.abspath(structures_dir))
        name = os.path.basename(organism_dir)
        candidates.extend([
            os.path.join(organism_dir, 'genome', f'{name}.gbk'),
            os.path.join(organism_dir, f'{name}.gbk'),
        ])

    for candidate in candidates:
        if os.path.isfile(candidate):
            return candidate

    raise FileNotFoundError('Could not find GBK file. Use --gbk-file.')


def load_locus_uniprot_mapping(structures_dir, organism_name):
    """
    Load locus_tag -> UniProt accession mapping generated by FastTarget.

    :param structures_dir: Path to organism/<organism>/structures.
    :param organism_name: Organism name used in the FastTarget run.
    :return: Dictionary keyed by locus_tag with UniProt accession values.
    """
    mapping_file = os.path.join(
        structures_dir,
        'uniprot_files',
        f'uniprot_{organism_name}_id_mapping.json'
    )
    if not files.file_check(mapping_file):
        raise FileNotFoundError(f'UniProt mapping file not found: {mapping_file}')

    mapping = files.json_to_dict(mapping_file)
    normalized = {}
    for locus_tag, uniprot_id in mapping.items():
        if isinstance(uniprot_id, list):
            uniprot_id = uniprot_id[0] if uniprot_id else None
        if uniprot_id:
            normalized[locus_tag] = str(uniprot_id)
    return normalized


def get_locus_sequences(gbk_file):
    """
    Extract translated CDS sequences keyed by locus_tag from a GenBank file.

    :param gbk_file: Path to the organism GenBank file.
    :return: Dictionary keyed by locus_tag with translated protein sequences.
    """
    sequences = {}
    for record in SeqIO.parse(gbk_file, 'genbank'):
        for feature in record.features:
            if feature.type != 'CDS':
                continue
            locus_tags = feature.qualifiers.get('locus_tag', [])
            translations = feature.qualifiers.get('translation', [])
            if not locus_tags or not translations:
                continue
            sequences[locus_tags[0]] = translations[0].replace('*', '')
    return sequences


def split_clean(value):
    """
    Split user-editable TSV fields that may contain pipe, comma, or semicolon lists.

    :param value: Raw TSV field value.
    :return: List of non-empty cleaned values.
    """
    if value is None:
        return []
    text = str(value).strip()
    if not text or text.lower() in ('nan', 'none', 'unknown'):
        return []
    return [item.strip() for item in re.split(r'[|;,]', text) if item.strip()]


def text_from_element(element):
    """
    Return all text from an XML element as a compact single line.

    :param element: XML element to parse.
    :return: String with normalized whitespace, or None.
    """
    if element is None:
        return None
    text = ' '.join(part.strip() for part in element.itertext() if part and part.strip())
    return re.sub(r'\s+', ' ', text).strip() or None


def first_xml_text_by_local_name(root, local_name):
    """
    Return the first text value from an XML tree matching a local tag name.

    :param root: XML root element.
    :param local_name: Tag local name without namespace.
    :return: Text value, or None.
    """
    for element in root.iter():
        if element.tag.split('}')[-1] == local_name and element.text:
            return element.text.strip()
    return None


def normalize_ligand_name(name):
    """
    Normalize ligand names for dictionary lookup and duplicate removal.

    :param name: Raw ligand name.
    :return: Normalized ligand name.
    """
    if not name:
        return ''
    name = re.sub(r'\s+', ' ', str(name)).strip()
    return name.rstrip('.')


def normalize_match_text(text):
    """
    Normalize chemical names for conservative string matching.

    :param text: Raw chemical name.
    :return: Normalized text for matching.
    """
    text = normalize_ligand_name(text).lower()
    text = text.replace('^{+}', '+').replace('^+', '+')
    text = text.replace('_{2}', '2').replace('_{3}', '3').replace('_{4}', '4')
    text = re.sub(r'[\s_{}]', '', text)
    return text


def unique_ligands(ligands):
    """
    Deduplicate ligand records by name and ChEBI ID.

    :param ligands: List of ligand dictionaries.
    :return: Deduplicated ligand dictionary list.
    """
    unique = []
    seen = set()
    for ligand in ligands:
        name = normalize_ligand_name(ligand.get('name'))
        chebi = ligand.get('chebi') or ''
        key = (name.lower(), chebi)
        if not name or key in seen:
            continue
        seen.add(key)
        clean_ligand = dict(ligand)
        clean_ligand['name'] = name
        unique.append(clean_ligand)
    return unique


def parse_reaction_substrates(reaction_text):
    """
    Parse only the substrate side of a UniProt catalytic reaction string.

    :param reaction_text: Raw reaction text from UniProt.
    :return: List of substrate names from the left side of the reaction.
    """
    if not reaction_text:
        return []
    text = re.sub(r'\s+', ' ', reaction_text).strip().rstrip('.')
    text = re.split(r'\s(?:=|<=>|->|=>)\s', text, maxsplit=1)[0]
    substrates = []
    for part in re.split(r'\s+\+\s+', text):
        part = re.sub(r'^\d+(\.\d+)?\s+', '', part.strip())
        part = re.sub(r'\s*\[[^\]]+\]\s*$', '', part)
        part = normalize_ligand_name(part)
        if part:
            substrates.append(part)
    return substrates


def chebi_soap_request(action, body):
    """
    Send a minimal ChEBI SOAP request and return the XML root.

    :param action: ChEBI SOAP action name.
    :param body: SOAP body XML content.
    :return: Parsed XML root element.
    """
    envelope = f"""<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:chebi="https://www.ebi.ac.uk/webservices/chebi">
  <soapenv:Header/>
  <soapenv:Body>
    {body}
  </soapenv:Body>
</soapenv:Envelope>"""
    headers = {
        'Content-Type': 'text/xml;charset=UTF-8',
        'SOAPAction': action,
        'User-Agent': 'FastTarget-Boltz/1.0',
    }
    response = requests.post(CHEBI_SOAP_URL, data=envelope.encode('utf-8'), headers=headers, timeout=40)
    response.raise_for_status()
    return ET.fromstring(response.content)


def fetch_chebi_complete_entity(chebi_id):
    """
    Fetch a complete ChEBI entity using REST first and SOAP as fallback.

    :param chebi_id: ChEBI identifier, e.g. CHEBI:12345.
    :return: Dictionary with ChEBI ID, name, and SMILES when available.
    """
    if not chebi_id:
        return {}
    rest_entity = fetch_chebi_complete_entity_rest(chebi_id)
    if rest_entity:
        return rest_entity

    chebi_id = xml_escape(str(chebi_id))
    body = f"""
<chebi:getCompleteEntity>
  <chebi:chebiId>{chebi_id}</chebi:chebiId>
</chebi:getCompleteEntity>"""
    try:
        root = chebi_soap_request('getCompleteEntity', body)
    except Exception as exc:
        logging.warning(f'ChEBI getCompleteEntity failed for {chebi_id}: {exc}')
        return {}

    synonyms = []
    for element in root.iter():
        local_name = element.tag.split('}')[-1]
        if local_name in ('chebiAsciiName', 'data', 'synonym') and element.text:
            synonyms.append(normalize_ligand_name(element.text))

    return {
        'chebi': first_xml_text_by_local_name(root, 'chebiId') or chebi_id,
        'name': first_xml_text_by_local_name(root, 'chebiAsciiName'),
        'smiles': first_xml_text_by_local_name(root, 'smiles'),
        'synonyms': sorted({synonym for synonym in synonyms if synonym}),
    }


def fetch_chebi_complete_entity_rest(chebi_id):
    """
    Fetch a complete ChEBI entity using the ChEBI JSON REST API.

    :param chebi_id: ChEBI identifier, e.g. CHEBI:12345.
    :return: Dictionary with ChEBI ID, name, SMILES, and synonyms when available.
    """
    if not chebi_id:
        return {}

    numeric_id = str(chebi_id).replace('CHEBI:', '').strip()
    if not numeric_id:
        return {}

    url = f'{CHEBI_REST_URL}/{numeric_id}/'
    params = {
        'only_ontology_parents': 'false',
        'only_ontology_children': 'false',
    }
    try:
        response = requests.get(url, params=params, timeout=40, headers={'User-Agent': 'FastTarget-Boltz/1.0'})
        if response.status_code == 404:
            return {}
        response.raise_for_status()
        data = response.json()
    except Exception as exc:
        logging.warning(f'ChEBI REST lookup failed for {chebi_id}: {exc}')
        return {}

    synonyms = []
    names = data.get('names') or {}
    for name_records in names.values():
        if not isinstance(name_records, list):
            continue
        for record in name_records:
            if not isinstance(record, dict):
                continue
            for key in ('ascii_name', 'name'):
                if record.get(key):
                    synonyms.append(normalize_ligand_name(record.get(key)))

    smiles = None
    default_structure = data.get('default_structure') or {}
    if isinstance(default_structure, dict):
        smiles = default_structure.get('smiles')

    return {
        'chebi': data.get('chebi_accession') or f'CHEBI:{numeric_id}',
        'name': data.get('ascii_name') or data.get('name'),
        'smiles': smiles,
        'synonyms': sorted({synonym for synonym in synonyms if synonym}),
    }


def fetch_rhea_reaction_participants(rhea_id):
    """
    Fetch Rhea reaction participant names and ChEBI IDs from the Rhea REST table.

    :param rhea_id: Rhea identifier, e.g. RHEA:16373.
    :return: Dictionary with equation, ChEBI names, and ChEBI IDs.
    """
    if not rhea_id:
        return {}
    params = {
        'query': rhea_id,
        'columns': 'rhea-id,equation,chebi,chebi-id',
        'format': 'tsv',
        'limit': 1,
    }
    try:
        response = requests.get(RHEA_TABLE_URL, params=params, timeout=40, headers={'User-Agent': 'FastTarget-Boltz/1.0'})
        response.raise_for_status()
        lines = [line for line in response.text.splitlines() if line.strip()]
        if len(lines) < 2:
            return {}
        header = lines[0].split('\t')
        values = lines[1].split('\t')
        row = dict(zip(header, values))
        return {
            'equation': row.get('Equation') or row.get('equation'),
            'chebi_names': split_clean(row.get('ChEBI name') or row.get('chebi') or ''),
            'chebi_ids': split_clean(row.get('ChEBI identifier') or row.get('chebi-id') or ''),
        }
    except Exception as exc:
        logging.warning(f'Rhea lookup failed for {rhea_id}: {exc}')
        return {}


def fetch_uniprot_batch_xml(uniprot_ids):
    """
    Fetch UniProt XML data for multiple UniProt IDs without importing structures.py.

    :param uniprot_ids: List of UniProt accession IDs.
    :return: XML content as bytes.
    """
    if not uniprot_ids:
        return b'<?xml version="1.0" encoding="UTF-8"?><uniprot xmlns="http://uniprot.org/uniprot"></uniprot>'

    ids_string = ','.join(uniprot_ids)
    uniprot_url = f'https://rest.uniprot.org/uniprotkb/accessions?accessions={ids_string}&format=xml'
    headers = {
        'User-Agent': 'FastTarget-Boltz/1.0',
        'Accept': 'application/xml',
    }
    response = requests.get(uniprot_url, headers=headers, timeout=60)
    response.raise_for_status()
    return response.content


def search_chebi_id_by_name(name):
    """
    Search ChEBI for a ligand name and return the first ChEBI ID.

    :param name: Ligand name.
    :return: ChEBI ID, or None.
    """
    if not name:
        return None
    search = xml_escape(str(name))
    body = f"""
<chebi:getLiteEntity>
  <chebi:search>{search}</chebi:search>
  <chebi:searchCategory>ALL</chebi:searchCategory>
  <chebi:maximumResults>1</chebi:maximumResults>
  <chebi:stars>ALL</chebi:stars>
</chebi:getLiteEntity>"""
    try:
        root = chebi_soap_request('getLiteEntity', body)
        return first_xml_text_by_local_name(root, 'chebiId')
    except Exception as exc:
        logging.warning(f'ChEBI name search failed for {name}: {exc}')
        return None


def fetch_pubchem_smiles(name):
    """
    Fetch canonical SMILES from PubChem by compound name as a fallback.

    :param name: Ligand name.
    :return: SMILES string, or None.
    """
    if not name:
        return None
    url = (
        'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/'
        f'{quote(name)}/property/CanonicalSMILES/TXT'
    )
    try:
        response = requests.get(url, timeout=30, headers={'User-Agent': 'FastTarget-Boltz/1.0'})
        if response.status_code == 404:
            return None
        response.raise_for_status()
        smiles = response.text.strip().splitlines()[0]
        return smiles or None
    except Exception as exc:
        logging.warning(f'PubChem SMILES lookup failed for {name}: {exc}')
        return None


def resolve_ligand_smiles(ligand, ligand_cache):
    """
    Resolve a UniProt ligand record to SMILES.

    :param ligand: Ligand dictionary with name and optional ChEBI ID.
    :param ligand_cache: Mutable cache keyed by ligand name/ChEBI ID.
    :return: Ligand dictionary with resolved SMILES metadata.
    """
    name = normalize_ligand_name(ligand.get('name'))
    chebi = ligand.get('chebi')
    cache_key = f'{chebi or ""}|{name.lower()}'
    if cache_key in ligand_cache:
        return dict(ligand_cache[cache_key])

    resolved = {
        'name': name,
        'chebi': chebi,
        'smiles': None,
        'source': None,
        'needs_manual_smiles': True,
    }

    if not chebi:
        chebi = search_chebi_id_by_name(name)
        resolved['chebi'] = chebi

    if chebi:
        entity = fetch_chebi_complete_entity(chebi)
        if entity.get('smiles'):
            resolved.update({
                'name': entity.get('name') or name,
                'chebi': entity.get('chebi') or chebi,
                'smiles': entity.get('smiles'),
                'source': 'chebi',
                'needs_manual_smiles': False,
            })
            ligand_cache[cache_key] = resolved
            return dict(resolved)

    if name in LOCAL_LIGAND_SMILES:
        resolved.update({
            'smiles': LOCAL_LIGAND_SMILES[name],
            'source': 'local',
            'needs_manual_smiles': False,
        })
        ligand_cache[cache_key] = resolved
        return dict(resolved)

    pubchem_smiles = fetch_pubchem_smiles(name)
    if pubchem_smiles:
        resolved.update({
            'smiles': pubchem_smiles,
            'source': 'pubchem',
            'needs_manual_smiles': False,
        })

    ligand_cache[cache_key] = resolved
    return dict(resolved)


def chebi_entity_matches_name(entity, name):
    """
    Check whether a ChEBI entity matches a substrate name.

    :param entity: Dictionary returned by fetch_chebi_complete_entity.
    :param name: Substrate name from the reaction left side.
    :return: True if the entity name or synonym matches the substrate name.
    """
    target = normalize_match_text(name)
    if not target:
        return False
    candidates = [entity.get('name')] + entity.get('synonyms', [])
    for candidate in candidates:
        candidate_norm = normalize_match_text(candidate)
        if candidate_norm and (candidate_norm == target or candidate_norm in target or target in candidate_norm):
            return True
    return False


def reaction_chebi_ids_from_rhea(rhea_ids):
    """
    Retrieve reaction participant ChEBI IDs from Rhea identifiers.

    :param rhea_ids: List of Rhea identifiers.
    :return: List of ChEBI identifiers.
    """
    chebi_ids = []
    for rhea_id in rhea_ids:
        rhea_data = fetch_rhea_reaction_participants(rhea_id)
        chebi_ids.extend(rhea_data.get('chebi_ids', []))
    return sorted(set(chebi_ids))


def match_substrate_ligands(substrate_names, reaction_chebi_ids, rhea_ids=None):
    """
    Match reaction-side substrate names to reaction participant ChEBI IDs.

    :param substrate_names: Substrate names parsed from the reaction left side.
    :param reaction_chebi_ids: ChEBI IDs listed in the UniProt reaction reference.
    :param rhea_ids: Optional Rhea identifiers used as fallback for participant ChEBIs.
    :return: List of ligand dictionaries with substrate name and matched ChEBI ID.
    """
    if not substrate_names:
        return []

    candidate_chebi_ids = list(reaction_chebi_ids or [])
    if not candidate_chebi_ids and rhea_ids:
        candidate_chebi_ids = reaction_chebi_ids_from_rhea(rhea_ids)

    candidate_entities = []
    for chebi_id in sorted(set(candidate_chebi_ids)):
        entity = fetch_chebi_complete_entity(chebi_id)
        if entity:
            candidate_entities.append(entity)

    matched = []
    for substrate_name in substrate_names:
        match = None
        for entity in candidate_entities:
            if chebi_entity_matches_name(entity, substrate_name):
                match = entity
                break
        if match:
            matched.append({
                'name': substrate_name,
                'chebi': match.get('chebi'),
            })
        else:
            matched.append({
                'name': substrate_name,
                'chebi': None,
            })
    return unique_ligands(matched)


def resolve_ligand_list(ligands, ligand_cache):
    """
    Resolve a list of ligand records to SMILES.

    :param ligands: List of ligand dictionaries.
    :param ligand_cache: Mutable ligand resolution cache.
    :return: List of resolved ligand dictionaries.
    """
    return [resolve_ligand_smiles(ligand, ligand_cache) for ligand in unique_ligands(ligands)]


def pipe_join(values):
    """
    Join non-empty values as a pipe-separated TSV field.

    :param values: Iterable of values.
    :return: Pipe-separated string or Unknown.
    """
    cleaned = [str(value) for value in values if value not in (None, '', UNKNOWN)]
    return '|'.join(cleaned) if cleaned else UNKNOWN


def parse_uniprot_boltz_entry(entry):
    """
    Parse the UniProt XML fields needed to create Boltz curation files.

    :param entry: UniProt XML entry element.
    :return: Dictionary with Boltz-relevant UniProt annotations, or None.
    """
    accession_el = entry.find('up:accession', UNIPROT_NS)
    if accession_el is None or not accession_el.text:
        return None

    accession = accession_el.text
    protein_name = UNKNOWN
    recommended = entry.find('up:protein/up:recommendedName/up:fullName', UNIPROT_NS)
    submitted = entry.find('up:protein/up:submittedName/up:fullName', UNIPROT_NS)
    if recommended is not None and recommended.text:
        protein_name = recommended.text
    elif submitted is not None and submitted.text:
        protein_name = submitted.text

    cofactors = []
    for comment in entry.findall('up:comment[@type="cofactor"]', UNIPROT_NS):
        comment_cofactors = []
        for cofactor_el in comment.findall('up:cofactor', UNIPROT_NS):
            name_el = cofactor_el.find('up:name', UNIPROT_NS)
            cofactor = {
                'name': name_el.text if name_el is not None and name_el.text else UNKNOWN,
                'chebi': None,
            }
            db_ref = cofactor_el.find('up:dbReference[@type="ChEBI"]', UNIPROT_NS)
            if db_ref is not None:
                cofactor['chebi'] = db_ref.get('id')
            comment_cofactors.append(cofactor)

        if comment_cofactors:
            cofactors.extend(comment_cofactors)
        else:
            text = text_from_element(comment)
            if text:
                cofactors.append({'name': text, 'chebi': None})

    catalytic_substrates = []
    for comment in entry.findall('up:comment[@type="catalytic activity"]', UNIPROT_NS):
        reaction = comment.find('up:reaction', UNIPROT_NS)
        reaction_text = text_from_element(reaction)
        if reaction is None:
            continue
        reaction_chebi_ids = [
            db_ref.get('id')
            for db_ref in reaction.findall('up:dbReference[@type="ChEBI"]', UNIPROT_NS)
            if db_ref.get('id')
        ]
        rhea_ids = [
            db_ref.get('id')
            for db_ref in reaction.findall('up:dbReference[@type="Rhea"]', UNIPROT_NS)
            if db_ref.get('id')
        ]
        substrate_names = parse_reaction_substrates(reaction_text)
        catalytic_substrates.extend(match_substrate_ligands(substrate_names, reaction_chebi_ids, rhea_ids))

    subunit_comment = entry.find('up:comment[@type="subunit"]', UNIPROT_NS)
    subunit_text = text_from_element(subunit_comment) or UNKNOWN
    quaternary_structure, copies = infer_quaternary_structure(subunit_text)

    sequence_el = entry.find('up:sequence', UNIPROT_NS)
    uniprot_sequence = None
    if sequence_el is not None and sequence_el.text:
        uniprot_sequence = re.sub(r'\s+', '', sequence_el.text)

    return {
        'uniprot_id': accession,
        'protein_name': protein_name,
        'cofactors': cofactors if cofactors else [],
        'catalytic_substrates': unique_ligands(catalytic_substrates),
        'subunit_text': subunit_text,
        'quaternary_structure': quaternary_structure,
        'copies': copies,
        'uniprot_sequence': uniprot_sequence,
    }


def infer_quaternary_structure(subunit_text):
    """
    Infer copy number from UniProt subunit text. Defaults to one copy for YAML creation.

    :param subunit_text: UniProt subunit comment text.
    :return: Tuple with inferred quaternary structure label and copy number.
    """
    if not subunit_text or subunit_text == UNKNOWN:
        return UNKNOWN, 1

    text = subunit_text.lower()
    patterns = [
        ('homodimer', 2),
        ('homotrimer', 3),
        ('homotetramer', 4),
        ('homopentamer', 5),
        ('homohexamer', 6),
        ('homoheptamer', 7),
        ('homooctamer', 8),
        ('homononamer', 9),
        ('homodecamer', 10),
        ('monomer', 1),
    ]
    for label, copies in patterns:
        if label in text:
            return label, copies

    if 'dimer' in text and 'heterodimer' not in text:
        return 'dimer', 2
    if 'trimer' in text and 'heterotrimer' not in text:
        return 'trimer', 3
    if 'tetramer' in text and 'heterotetramer' not in text:
        return 'tetramer', 4
    if 'hexamer' in text and 'heterohexamer' not in text:
        return 'hexamer', 6

    return UNKNOWN, 1


def fetch_uniprot_boltz_annotations(uniprot_ids, batch_size=100):
    """
    Fetch UniProt annotations in batches using the existing FastTarget UniProt helper.

    :param uniprot_ids: Iterable of UniProt accession IDs.
    :param batch_size: Number of UniProt IDs to request per batch.
    :return: Dictionary keyed by UniProt accession with parsed annotations.
    """
    annotations = {}
    unique_ids = sorted({uid for uid in uniprot_ids if uid})
    for index in tqdm(range(0, len(unique_ids), batch_size), desc='UniProt batches'):
        batch = unique_ids[index:index + batch_size]
        try:
            xml_content = fetch_uniprot_batch_xml(batch)
            root = ET.fromstring(xml_content)
            for entry in root.findall('up:entry', UNIPROT_NS):
                parsed = parse_uniprot_boltz_entry(entry)
                if parsed:
                    annotations[parsed['uniprot_id']] = parsed
        except Exception as exc:
            logging.exception(f'Failed to fetch UniProt batch {batch}: {exc}')
            for uniprot_id in batch:
                annotations.setdefault(uniprot_id, {
                    'uniprot_id': uniprot_id,
                    'protein_name': UNKNOWN,
                    'cofactors': [],
                    'catalytic_substrates': [],
                    'subunit_text': UNKNOWN,
                    'quaternary_structure': UNKNOWN,
                    'copies': 1,
                    'uniprot_sequence': None,
                })
    return annotations


def build_boltz_annotations(mapping, sequences, refresh_uniprot=False, annotations_json=None):
    """
    Build locus-keyed Boltz annotations from mapping, GBK sequences, and UniProt.

    :param mapping: Dictionary keyed by locus_tag with UniProt accession values.
    :param sequences: Dictionary keyed by locus_tag with protein sequences.
    :param refresh_uniprot: If True, ignore existing annotation JSON and fetch again.
    :param annotations_json: Existing Boltz annotations JSON path, if available.
    :return: Dictionary keyed by locus_tag with Boltz annotations.
    """
    existing = {}
    if annotations_json and os.path.isfile(annotations_json) and not refresh_uniprot:
        existing = files.json_to_dict(annotations_json)

    missing_loci = [locus for locus in mapping if locus not in existing]
    uniprot_annotations = fetch_uniprot_boltz_annotations([mapping[locus] for locus in missing_loci])
    ligand_cache = {}

    annotations = dict(existing)
    for locus_tag, uniprot_id in mapping.items():
        if locus_tag in annotations and not refresh_uniprot:
            continue
        uniprot_data = uniprot_annotations.get(uniprot_id, {})
        cofactors = uniprot_data.get('cofactors') or []
        catalytic_substrates = uniprot_data.get('catalytic_substrates') or []
        resolved_cofactors = resolve_ligand_list(cofactors, ligand_cache)
        resolved_substrates = resolve_ligand_list(catalytic_substrates, ligand_cache)
        selected_ligands = unique_ligands(resolved_cofactors + resolved_substrates)
        annotations[locus_tag] = {
            'locus_tag': locus_tag,
            'uniprot_id': uniprot_id,
            'protein_name': uniprot_data.get('protein_name') or UNKNOWN,
            'sequence': sequences.get(locus_tag),
            'sequence_length': len(sequences.get(locus_tag, '')) if sequences.get(locus_tag) else None,
            'cofactors': cofactors if cofactors else UNKNOWN,
            'resolved_cofactors': resolved_cofactors if resolved_cofactors else UNKNOWN,
            'catalytic_substrates': catalytic_substrates if catalytic_substrates else UNKNOWN,
            'resolved_catalytic_substrates': resolved_substrates if resolved_substrates else UNKNOWN,
            'selected_ligands': selected_ligands if selected_ligands else UNKNOWN,
            'subunit_text': uniprot_data.get('subunit_text') or UNKNOWN,
            'quaternary_structure': uniprot_data.get('quaternary_structure') or UNKNOWN,
            'copies': int(uniprot_data.get('copies') or 1),
            'boltz': {
                'run': bool(sequences.get(locus_tag)),
                'needs_manual_check': any(
                    ligand.get('needs_manual_smiles')
                    for ligand in selected_ligands
                    if isinstance(ligand, dict)
                ),
            },
        }
    return annotations


def write_annotations_json(annotations, annotations_json):
    """
    Write Boltz annotations to JSON.

    :param annotations: Dictionary keyed by locus_tag with Boltz annotations.
    :param annotations_json: Output JSON path.
    """
    with open(annotations_json, 'w') as handle:
        json.dump(annotations, handle, indent=4)
    print(f'Boltz annotations saved to {annotations_json}')


def cofactor_names(cofactors):
    """
    Convert parsed UniProt cofactor records into a compact TSV field.

    :param cofactors: List of cofactor dictionaries or Unknown.
    :return: Pipe-separated cofactor names, or Unknown.
    """
    if not cofactors or cofactors == UNKNOWN:
        return UNKNOWN
    return '|'.join(sorted({cof.get('name', UNKNOWN) for cof in cofactors if cof.get('name')})) or UNKNOWN


def ligand_field(ligands, field):
    """
    Convert ligand dictionaries into a pipe-separated TSV field.

    :param ligands: List of ligand dictionaries or Unknown.
    :param field: Ligand dictionary field to extract.
    :return: Pipe-separated values, or Unknown.
    """
    if not ligands or ligands == UNKNOWN:
        return UNKNOWN
    values = []
    for ligand in ligands:
        if isinstance(ligand, dict) and ligand.get(field):
            values.append(ligand.get(field))
    return pipe_join(values)


def write_curation_tsv(annotations, curation_tsv, overwrite=False):
    """
    Write a user-editable TSV. Existing TSV is kept unless overwrite=True.

    :param annotations: Dictionary keyed by locus_tag with Boltz annotations.
    :param curation_tsv: Output TSV path.
    :param overwrite: If True, overwrite an existing curation TSV.
    """
    if os.path.isfile(curation_tsv) and not overwrite:
        print(f'Curation TSV already exists, keeping user edits: {curation_tsv}')
        return

    fieldnames = [
        'run_boltz',
        'locus_tag',
        'uniprot_id',
        'protein_name',
        'sequence_length',
        'quaternary_structure',
        'copies',
        'subunit_text',
        'cofactors_uniprot_raw',
        'cofactor_chebi_ids',
        'cofactor_smiles',
        'substrates_uniprot_raw',
        'substrate_chebi_ids',
        'substrate_smiles',
        'selected_ligand_names',
        'selected_ligand_smiles',
        'ligand_resolution_sources',
        'ligand_needs_review',
        'notes',
    ]
    with open(curation_tsv, 'w', newline='') as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter='\t')
        writer.writeheader()
        for locus_tag in sorted(annotations):
            ann = annotations[locus_tag]
            writer.writerow({
                'run_boltz': 'True' if ann.get('sequence') else 'False',
                'locus_tag': locus_tag,
                'uniprot_id': ann.get('uniprot_id') or '',
                'protein_name': ann.get('protein_name') or UNKNOWN,
                'sequence_length': ann.get('sequence_length') or '',
                'quaternary_structure': ann.get('quaternary_structure') or UNKNOWN,
                'copies': ann.get('copies') or 1,
                'subunit_text': ann.get('subunit_text') or UNKNOWN,
                'cofactors_uniprot_raw': cofactor_names(ann.get('cofactors')),
                'cofactor_chebi_ids': ligand_field(ann.get('resolved_cofactors'), 'chebi'),
                'cofactor_smiles': ligand_field(ann.get('resolved_cofactors'), 'smiles'),
                'substrates_uniprot_raw': cofactor_names(ann.get('catalytic_substrates')),
                'substrate_chebi_ids': ligand_field(ann.get('resolved_catalytic_substrates'), 'chebi'),
                'substrate_smiles': ligand_field(ann.get('resolved_catalytic_substrates'), 'smiles'),
                'selected_ligand_names': ligand_field(ann.get('selected_ligands'), 'name'),
                'selected_ligand_smiles': ligand_field(ann.get('selected_ligands'), 'smiles'),
                'ligand_resolution_sources': ligand_field(ann.get('selected_ligands'), 'source'),
                'ligand_needs_review': ann.get('boltz', {}).get('needs_manual_check', True),
                'notes': 'Curate selected_ligand_smiles before Boltz. Substrates are all reported for now.',
            })
    print(f'Curation TSV saved to {curation_tsv}')


def read_curation_tsv(curation_tsv):
    """
    Read user-curated Boltz parameters from TSV.

    :param curation_tsv: Path to boltz_curation.tsv.
    :return: Dictionary keyed by locus_tag with run flag, copies, and ligands.
    """
    if not os.path.isfile(curation_tsv):
        raise FileNotFoundError(f'Curation TSV not found: {curation_tsv}')
    df = pd.read_csv(curation_tsv, sep='\t', dtype=str, keep_default_na=False)
    curation = {}
    for _, row in df.iterrows():
        locus_tag = row.get('locus_tag', '').strip()
        if not locus_tag:
            continue
        run_value = row.get('run_boltz', 'True').strip().lower()
        try:
            copies = int(row.get('copies', '1') or 1)
        except ValueError:
            copies = 1
        curation[locus_tag] = {
            'run_boltz': run_value in ('true', '1', 'yes', 'y'),
            'copies': max(copies, 1),
            'quaternary_structure': row.get('quaternary_structure', UNKNOWN) or UNKNOWN,
            'cofactors_uniprot': (
                row.get('cofactors_uniprot_raw')
                or row.get('cofactors_uniprot')
                or UNKNOWN
            ),
            'substrates_uniprot': row.get('substrates_uniprot_raw', UNKNOWN) or UNKNOWN,
            'cofactor_ccds': split_clean(row.get('cofactor_ccds', '')),
            'cofactor_smiles': split_clean(row.get('cofactor_smiles', '')),
            'selected_ligand_names': split_clean(row.get('selected_ligand_names', '')),
            'selected_ligand_smiles': split_clean(
                row.get('selected_ligand_smiles')
                or row.get('cofactor_smiles', '')
            ),
        }
    return curation


def chain_ids(copies):
    """
    Create Boltz protein chain IDs for the requested copy number.

    :param copies: Number of protein copies in the model.
    :return: List of chain IDs.
    """
    alphabet = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    if copies <= len(alphabet):
        return alphabet[:copies]
    return [f'A{i + 1}' for i in range(copies)]


def ligand_ids(prefix, copies):
    """
    Create ligand IDs, assuming one ligand per protein copy.

    :param prefix: Ligand ID prefix.
    :param copies: Number of protein copies.
    :return: List of ligand IDs.
    """
    prefix = re.sub(r'\([^)]*\)', '', str(prefix))
    safe_prefix = re.sub(r'[^A-Za-z0-9]', '', prefix.upper()) or 'LIG'
    return [f'{safe_prefix}{i + 1}' for i in range(copies)]


def ligand_id_prefix(name, index, total):
    """
    Create a compact ligand ID prefix from a ligand name.

    :param name: Ligand name.
    :param index: One-based ligand index.
    :param total: Total number of ligands in the YAML.
    :return: Ligand ID prefix.
    """
    if name:
        cleaned = re.sub(r'\([^)]*\)', '', str(name))
        cleaned = re.sub(r'[^A-Za-z0-9]', '', cleaned.upper())
        if 1 <= len(cleaned) <= 6:
            return cleaned
    return 'LIG' if total == 1 else f'L{index}'


def build_boltz_yaml_dict(locus_tag, sequence, curation):
    """
    Build the Boltz YAML data structure for one locus tag.

    :param locus_tag: Locus tag identifier.
    :param sequence: Protein sequence.
    :param curation: Curated Boltz parameters for the locus.
    :return: Dictionary ready to write as YAML.
    """
    copies = curation['copies']
    yaml_dict = {
        'version': 1,
        'sequences': [
            {
                'protein': {
                    'id': chain_ids(copies),
                    'sequence': sequence,
                }
            }
        ]
    }

    smiles_values = curation.get('selected_ligand_smiles') or curation.get('cofactor_smiles', [])
    ligand_names = curation.get('selected_ligand_names', [])
    for idx, smiles in enumerate(smiles_values, start=1):
        name = ligand_names[idx - 1] if idx <= len(ligand_names) else None
        prefix = ligand_id_prefix(name, idx, len(smiles_values))
        yaml_dict['sequences'].append({
            'ligand': {
                'id': ligand_ids(prefix, copies),
                'smiles': smiles,
            }
        })

    return yaml_dict


def write_boltz_yaml_files(annotations, curation, inputs_dir):
    """
    Write one YAML input per locus selected in the curation TSV.

    :param annotations: Dictionary keyed by locus_tag with Boltz annotations.
    :param curation: Dictionary keyed by locus_tag with curated Boltz parameters.
    :param inputs_dir: Directory where YAML files will be written.
    :return: Dictionary keyed by locus_tag with YAML paths.
    """
    yaml_files = {}
    for locus_tag in sorted(annotations):
        ann = annotations[locus_tag]
        cur = curation.get(locus_tag)
        sequence = ann.get('sequence')
        if not cur or not cur['run_boltz'] or not sequence:
            continue

        yaml_path = os.path.join(inputs_dir, f'{locus_tag}.yaml')
        yaml_data = build_boltz_yaml_dict(locus_tag, sequence, cur)
        with open(yaml_path, 'w') as handle:
            handle.write(f'# {locus_tag}\n')
            yaml.safe_dump(yaml_data, handle, sort_keys=False, width=120)
        yaml_files[locus_tag] = yaml_path

    print(f'Boltz YAML files written: {len(yaml_files)}')
    return yaml_files


def run_boltz_predict(inputs_dir, results_dir, cache, use_msa_server=True, output_format='pdb', boltz_executable='boltz'):
    """
    Run Boltz on a folder of YAML files.

    :param inputs_dir: Directory containing Boltz YAML files.
    :param results_dir: Directory where Boltz will write outputs.
    :param cache: Boltz cache path.
    :param use_msa_server: If True, pass --use_msa_server.
    :param output_format: Boltz output structure format.
    :param boltz_executable: Boltz executable name or path.
    """
    cmd = [
        boltz_executable,
        'predict',
        inputs_dir,
    ]
    if use_msa_server:
        cmd.append('--use_msa_server')
    cmd.extend([
        '--out_dir',
        results_dir,
        '--cache',
        cache,
        '--output_format',
        output_format,
    ])

    print('Running:', ' '.join(cmd))
    subprocess.run(cmd, check=True)


def model_sort_key(path):
    """
    Sort Boltz model candidates so preferred model names are selected first.

    :param path: Candidate model path.
    :return: Sort key tuple.
    """
    name = os.path.basename(path).lower()
    score = 0
    if 'model_0' in name or 'rank_001' in name or 'rank_1' in name:
        score -= 100
    if name.endswith('.pdb'):
        score -= 10
    return score, name


def find_best_boltz_model(results_dir, locus_tag):
    """
    Find the preferred Boltz model for a locus tag.

    :param results_dir: Boltz results directory.
    :param locus_tag: Locus tag identifier.
    :return: Path to the selected model file, or None.
    """
    search_roots = [
        os.path.join(results_dir, 'predictions', locus_tag),
        os.path.join(results_dir, locus_tag),
        results_dir,
    ]
    candidates = []
    for root in search_roots:
        if os.path.isdir(root):
            candidates.extend(glob.glob(os.path.join(root, '**', '*.pdb'), recursive=True))
            candidates.extend(glob.glob(os.path.join(root, '**', '*.cif'), recursive=True))

    candidates = [
        path for path in candidates
        if os.path.isfile(path) and locus_tag.lower() in os.path.basename(path).lower()
    ] or [path for path in candidates if os.path.isfile(path)]

    if not candidates:
        return None
    return sorted(set(candidates), key=model_sort_key)[0]


def normalize_boltz_models(yaml_files, results_dir, models_dir):
    """
    Copy best Boltz models into a single folder named BZ_<locus_tag>.<ext>.

    :param yaml_files: Dictionary keyed by locus_tag with YAML paths.
    :param results_dir: Boltz results directory.
    :param models_dir: Directory where normalized models will be copied.
    :return: Dictionary keyed by locus_tag with normalized model paths.
    """
    model_paths = {}
    for locus_tag in tqdm(sorted(yaml_files), desc='Normalizing Boltz models'):
        source = find_best_boltz_model(results_dir, locus_tag)
        if not source:
            logging.warning(f'No Boltz model found for {locus_tag}')
            continue
        ext = os.path.splitext(source)[1].lower()
        dest = os.path.join(models_dir, f'BZ_{locus_tag}{ext}')
        shutil.copy2(source, dest)
        model_paths[locus_tag] = dest
    print(f'Normalized Boltz models: {len(model_paths)}')
    return model_paths


def find_confidence_json(results_dir, locus_tag):
    """
    Find Boltz confidence JSON for one locus tag.

    :param results_dir: Boltz results directory.
    :param locus_tag: Locus tag identifier.
    :return: Path to confidence JSON, or None.
    """
    candidates = []
    roots = [
        os.path.join(results_dir, 'predictions', locus_tag),
        os.path.join(results_dir, locus_tag),
        results_dir,
    ]
    for root in roots:
        if os.path.isdir(root):
            candidates.extend(glob.glob(os.path.join(root, '**', f'confidence*{locus_tag}*.json'), recursive=True))
            candidates.extend(glob.glob(os.path.join(root, '**', 'confidence*.json'), recursive=True))
    return sorted(set(candidates))[0] if candidates else None


def parse_model_confidence(results_dir, locus_tag):
    """
    Parse Boltz confidence metrics for one locus tag.

    :param results_dir: Boltz results directory.
    :param locus_tag: Locus tag identifier.
    :return: Dictionary with selected confidence metrics.
    """
    confidence_json = find_confidence_json(results_dir, locus_tag)
    if not confidence_json:
        return {}
    try:
        with open(confidence_json) as handle:
            data = json.load(handle)
        keys = [
            'confidence_score',
            'ptm',
            'iptm',
            'ligand_iptm',
            'protein_iptm',
            'complex_plddt',
            'complex_iplddt',
        ]
        return {key: data.get(key) for key in keys}
    except Exception as exc:
        logging.warning(f'Could not parse confidence JSON for {locus_tag}: {exc}')
        return {}


def run_boltz_pockets(model_paths, pockets_dir, container_engine='docker', cpus=1):
    """
    Run FPocket and P2Rank for normalized Boltz PDB models.

    :param model_paths: Dictionary keyed by locus_tag with normalized model paths.
    :param pockets_dir: Directory where pocket outputs will be written.
    :param container_engine: Container engine for FPocket and P2Rank.
    :param cpus: Number of CPUs for P2Rank.
    """
    structures = get_structures_module()
    for locus_tag, model_path in tqdm(model_paths.items(), desc='Boltz pocket prediction'):
        if not model_path.endswith('.pdb'):
            logging.warning(f'Skipping pockets for non-PDB Boltz model: {model_path}')
            continue

        locus_pockets_dir = os.path.join(pockets_dir, locus_tag)
        os.makedirs(locus_pockets_dir, exist_ok=True)
        model_parent = os.path.dirname(model_path)

        try:
            structures.fpocket_for_structure(model_path, model_parent, locus_pockets_dir, container_engine=container_engine)
        except Exception as exc:
            logging.exception(f'FPocket failed for {locus_tag}: {exc}')

        try:
            structures.p2rank_for_structure(
                model_path,
                model_parent,
                locus_pockets_dir,
                cpus,
                alphafold=True,
                container_engine=container_engine
            )
        except Exception as exc:
            logging.exception(f'P2Rank failed for {locus_tag}: {exc}')


def parse_best_fpocket(locus_pockets_dir):
    """
    Parse the best FPocket result from a Boltz locus pocket directory.

    :param locus_pockets_dir: Path to structures/boltz/pockets/<locus_tag>.
    :return: Tuple with druggability score and pocket ID.
    """
    structures = get_structures_module()
    folders = [
        os.path.join(locus_pockets_dir, folder)
        for folder in os.listdir(locus_pockets_dir)
        if folder.endswith('_fpocket') and os.path.isdir(os.path.join(locus_pockets_dir, folder))
    ] if os.path.isdir(locus_pockets_dir) else []
    if not folders:
        return None, None
    pockets_dict = structures.pockets_data_to_dict(folders[0])
    best = structures.pockets_filter(pockets_dict)
    key = next(iter(best.keys()), None)
    value = best.get(key) if key else None
    if value == 'No_pockets' or not isinstance(value, dict):
        return None, 'No_pockets'
    return value.get('maxDS'), value.get('pocket')


def parse_best_p2rank(locus_pockets_dir):
    """
    Parse the best P2Rank result from a Boltz locus pocket directory.

    :param locus_pockets_dir: Path to structures/boltz/pockets/<locus_tag>.
    :return: Tuple with P2Rank probability and pocket ID.
    """
    structures = get_structures_module()
    folders = [
        os.path.join(locus_pockets_dir, folder)
        for folder in os.listdir(locus_pockets_dir)
        if folder.endswith('_p2rank') and os.path.isdir(os.path.join(locus_pockets_dir, folder))
    ] if os.path.isdir(locus_pockets_dir) else []
    if not folders:
        return None, None
    p2rank_dict = structures.p2rank_data_to_dict(folders[0])
    best = structures.p2rank_filter(p2rank_dict)
    key = next(iter(best.keys()), None)
    value = best.get(key) if key else None
    if value == 'No_pockets' or not isinstance(value, dict):
        return None, 'No_pockets'
    return value.get('max_probability'), value.get('pocket')


def write_boltz_summary(annotations, curation, model_paths, results_dir, pockets_dir, summary_tsv):
    """
    Write mergeable Boltz summary table.

    :param annotations: Dictionary keyed by locus_tag with Boltz annotations.
    :param curation: Dictionary keyed by locus_tag with curated Boltz parameters.
    :param model_paths: Dictionary keyed by locus_tag with normalized model paths.
    :param results_dir: Boltz results directory.
    :param pockets_dir: Boltz pockets directory.
    :param summary_tsv: Output summary TSV path.
    :return: Summary table as a pandas DataFrame.
    """
    rows = []
    for locus_tag in sorted(curation):
        cur = curation[locus_tag]
        if not cur['run_boltz']:
            continue
        ann = annotations.get(locus_tag, {})
        model_path = model_paths.get(locus_tag)
        confidence = parse_model_confidence(results_dir, locus_tag)
        fpocket_score, fpocket_pocket = parse_best_fpocket(os.path.join(pockets_dir, locus_tag))
        p2rank_score, p2rank_pocket = parse_best_p2rank(os.path.join(pockets_dir, locus_tag))

        rows.append({
            'gene': locus_tag,
            'uniprot': ann.get('uniprot_id'),
            'boltz_structure': os.path.basename(model_path) if model_path else None,
            'boltz_model_path': model_path,
            'boltz_quaternary_structure': cur.get('quaternary_structure'),
            'boltz_copies': cur.get('copies'),
            'boltz_cofactors_uniprot': cur.get('cofactors_uniprot'),
            'boltz_substrates_uniprot': cur.get('substrates_uniprot'),
            'boltz_selected_ligand_names': '|'.join(cur.get('selected_ligand_names', [])),
            'boltz_selected_ligand_smiles': '|'.join(cur.get('selected_ligand_smiles', [])),
            'boltz_confidence_score': confidence.get('confidence_score'),
            'boltz_ptm': confidence.get('ptm'),
            'boltz_iptm': confidence.get('iptm'),
            'boltz_ligand_iptm': confidence.get('ligand_iptm'),
            'boltz_protein_iptm': confidence.get('protein_iptm'),
            'boltz_complex_plddt': confidence.get('complex_plddt'),
            'boltz_complex_iplddt': confidence.get('complex_iplddt'),
            'boltz_druggability_score': fpocket_score,
            'boltz_fpocket_pocket': fpocket_pocket,
            'boltz_p2rank_probability': p2rank_score,
            'boltz_p2rank_pocket': p2rank_pocket,
        })

    df = pd.DataFrame(rows)
    df.to_csv(summary_tsv, sep='\t', index=False)
    print(f'Boltz summary table saved to {summary_tsv}')
    return df


def build_arg_parser():
    """
    Build command-line argument parser.

    :return: Configured argparse.ArgumentParser.
    """
    parser = argparse.ArgumentParser(
        description='Standalone Boltz workflow for FastTarget structure results.'
    )
    parser.add_argument('--output-path', default=None, help='FastTarget output path containing organism folders.')
    parser.add_argument('--organism-name', default=None, help='Organism name used by FastTarget.')
    parser.add_argument('--structures-dir', default=None, help='Direct path to organism/<organism>/structures.')
    parser.add_argument('--gbk-file', default=None, help='Path to the organism GenBank file.')
    parser.add_argument('--cache', default='/grupos/Marce/estructural/boltz/boltz_cache', help='Boltz cache path.')
    parser.add_argument('--boltz-executable', default='boltz', help='Boltz executable name/path.')
    parser.add_argument('--container-engine', default='docker', choices=['docker', 'singularity', 'apptainer'], help='Container engine for FPocket/P2Rank.')
    parser.add_argument('--cpus', type=int, default=1, help='CPUs for P2Rank.')
    parser.add_argument('--stage', default='all', choices=['annotations', 'yaml', 'predict', 'models', 'pockets', 'summary', 'all'], help='Workflow stage to run.')
    parser.add_argument('--refresh-uniprot', action='store_true', help='Refetch UniProt annotations even if JSON exists.')
    parser.add_argument('--overwrite-curation', action='store_true', help='Overwrite existing curation TSV.')
    parser.add_argument('--skip-boltz-run', action='store_true', help='Create inputs and parse existing results without running boltz predict.')
    parser.add_argument('--skip-pockets', action='store_true', help='Skip FPocket/P2Rank execution and only parse existing pocket outputs.')
    parser.add_argument('--no-msa-server', action='store_true', help='Do not pass --use_msa_server to Boltz.')
    return parser


def main(argv=None):
    """
    Run the standalone Boltz workflow.

    :param argv: Optional list of command-line arguments.
    """
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    organism_name, structures_dir = infer_organism_name(args.output_path, args.organism_name, args.structures_dir)
    if not os.path.isdir(structures_dir):
        raise FileNotFoundError(f'Structures directory not found: {structures_dir}')

    dirs = create_boltz_folders(structures_dir)
    annotations_json = os.path.join(dirs['boltz'], 'boltz_annotations.json')
    curation_tsv = os.path.join(dirs['boltz'], 'boltz_curation.tsv')
    summary_tsv = os.path.join(dirs['boltz'], f'{organism_name}_boltz_summary.tsv')

    gbk_file = find_gbk_file(args.output_path, organism_name, args.gbk_file, structures_dir)
    mapping = load_locus_uniprot_mapping(structures_dir, organism_name)
    sequences = get_locus_sequences(gbk_file)

    stages = ['annotations', 'yaml', 'predict', 'models', 'pockets', 'summary'] if args.stage == 'all' else [args.stage]

    annotations = None
    if 'annotations' in stages or not os.path.isfile(annotations_json):
        annotations = build_boltz_annotations(mapping, sequences, args.refresh_uniprot, annotations_json)
        write_annotations_json(annotations, annotations_json)
        write_curation_tsv(annotations, curation_tsv, overwrite=args.overwrite_curation)
    else:
        annotations = files.json_to_dict(annotations_json)

    curation = read_curation_tsv(curation_tsv)

    yaml_files = {}
    if any(stage in stages for stage in ['yaml', 'predict', 'models', 'pockets', 'summary']):
        yaml_files = write_boltz_yaml_files(annotations, curation, dirs['inputs'])

    if 'predict' in stages and not args.skip_boltz_run:
        run_boltz_predict(
            dirs['inputs'],
            dirs['results'],
            args.cache,
            use_msa_server=not args.no_msa_server,
            output_format='pdb',
            boltz_executable=args.boltz_executable,
        )

    model_paths = {}
    if any(stage in stages for stage in ['models', 'pockets', 'summary']):
        model_paths = normalize_boltz_models(yaml_files, dirs['results'], dirs['models'])

    if 'pockets' in stages and not args.skip_pockets:
        run_boltz_pockets(model_paths, dirs['pockets'], container_engine=args.container_engine, cpus=args.cpus)

    if 'summary' in stages:
        if not model_paths:
            model_paths = normalize_boltz_models(yaml_files, dirs['results'], dirs['models'])
        write_boltz_summary(annotations, curation, model_paths, dirs['results'], dirs['pockets'], summary_tsv)


if __name__ == '__main__':
    main()
