############################################################
# Dockerfile to build a BioPerl container image
# Based on Ubuntu with Perl
############################################################

# Use an official Ubuntu base image
FROM ubuntu:latest

# Maintainer label
LABEL maintainer="mcpalumbo"

# Update packages and install BioPerl
RUN apt-get update && \
    apt-get install -y \
    perl \
    bioperl \
    curl \
    libexpat1-dev \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the default working directory when starting the container
WORKDIR /data

# Default command when starting the container
CMD ["perl"]
